2025-05-18 13:53:32,296 Fetching artfiact
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/apis/public/api.py", line 958, in artifact
    artifact = wandb.Artifact._from_name(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 252, in _from_name
    attrs = response.get("project", {}).get("artifact")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/sjwalker/nd0821-c2-build-model-workflow-exercises-4/lesson-2-data-exploration-and-preparation/exercises/exercise_5/starter/run.py", line 73, in <module>
    go(args)
  File "/home/sjwalker/nd0821-c2-build-model-workflow-exercises-4/lesson-2-data-exploration-and-preparation/exercises/exercise_5/starter/run.py", line 17, in go
    artifact = run.use_artifact(f"{args.input_artifact}")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2783, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/apis/public/api.py", line 958, in artifact
    artifact = wandb.Artifact._from_name(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjwalker/miniconda3/envs/mlflow-b58d5b8bb9dbe5b3e3bb4ce455d4705a88104166/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 252, in _from_name
    attrs = response.get("project", {}).get("artifact")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb.errors.CommError: 'NoneType' object has no attribute 'get'